from p2s_core.models import EvidenceSpan, PaperClaim
from p2s_core.reviewers import Arbiter, ClaimEvidenceReviewer, PaperFidelityReviewer


SOURCE_TEXT = """Results

The proposed method improves accuracy by 5 percent on the benchmark dataset.

Limitations

The method has only been evaluated on English-language data."""


def make_claim(**overrides):
    data = {
        "claim_id": "claim_001",
        "claim_text": "The proposed method improves accuracy by 5 percent.",
        "claim_type": "result",
        "source_section": "result",
        "evidence_spans": [
            EvidenceSpan(
                section="Results",
                text="The proposed method improves accuracy by 5 percent on the benchmark dataset.",
            )
        ],
        "certainty": "explicit",
        "importance": 4,
    }
    data.update(overrides)
    return PaperClaim(**data)


def test_claim_evidence_missing_evidence_critical_fail():
    claim = make_claim(evidence_spans=[])

    review = ClaimEvidenceReviewer().review(claim, SOURCE_TEXT)

    assert review.pass_gate is False
    assert review.severity == "critical"
    assert review.target_id == "claim_001"


def test_claim_evidence_unmatched_evidence_high_fail():
    claim = make_claim(
        evidence_spans=[
            EvidenceSpan(
                section="Results",
                text="This evidence sentence does not exist anywhere in the extracted paper text.",
            )
        ]
    )

    review = ClaimEvidenceReviewer().review(claim, SOURCE_TEXT)

    assert review.pass_gate is False
    assert review.severity == "high"


def test_claim_evidence_direct_match_passes():
    review = ClaimEvidenceReviewer().review(make_claim(), SOURCE_TEXT)

    assert review.pass_gate is True
    assert review.severity == "low"


def test_claim_evidence_matches_across_pdf_line_breaks():
    source = "We say that subliminal learning occurs when the student training\n" \
        "data are not semantically related to the trait and the student learns\n" \
        "the trait."
    claim = make_claim(
        claim_text="Subliminal learning occurs without semantic relation to the trait.",
        evidence_spans=[
            EvidenceSpan(
                section="Method",
                text="We say that subliminal learning occurs when the student training data are not semantically related to the trait and the student learns the trait.",
            )
        ],
    )

    review = ClaimEvidenceReviewer().review(claim, source)

    assert review.pass_gate is True


def test_claim_evidence_matches_pdf_hyphenation():
    source = "Subliminal learning on MNIST (a toy setting) requires that the stu-\n" \
        "dent starts out similar to the initial state of teacher."
    claim = make_claim(
        claim_text="MNIST subliminal learning requires similar initialization.",
        evidence_spans=[
            EvidenceSpan(
                section="Discussion",
                text="Subliminal learning on MNIST (a toy setting) requires that the student starts out similar to the initial state of teacher.",
            )
        ],
    )

    review = ClaimEvidenceReviewer().review(claim, source)

    assert review.pass_gate is True


def test_claim_evidence_fuzzy_matches_quote_with_parenthetical_insert():
    source = "we show that training on number sequences generated by a misaligned\n" \
        "teacher can cause misalignment (even if numbers with known negative\n" \
        "associations are removed)."
    claim = make_claim(
        claim_text="Training on number sequences can transmit misalignment.",
        evidence_spans=[
            EvidenceSpan(
                section="Results",
                text="we show that training on number sequences generated by a misaligned teacher can cause misalignment.",
            )
        ],
    )

    review = ClaimEvidenceReviewer().review(claim, source)

    assert review.pass_gate is True


def test_paper_fidelity_overhyped_claim_high_fail():
    claim = make_claim(claim_text="The method completely solves benchmark reasoning.")

    review = PaperFidelityReviewer().review(claim)

    assert review.pass_gate is False
    assert review.severity == "high"
    assert "completely solves" in review.findings[0]


def test_arbiter_rejects_when_critical_ratio_is_high():
    claim = make_claim(evidence_spans=[])
    review = ClaimEvidenceReviewer().review(claim, SOURCE_TEXT)

    decision = Arbiter().decide([review], total_claims=1)

    assert decision.status == "reject"
    assert decision.target_type == "artifact"


def test_arbiter_human_check_for_high_fail():
    claim = make_claim(claim_text="The method completely solves benchmark reasoning.")
    review = PaperFidelityReviewer().review(claim)

    decision = Arbiter().decide([review], total_claims=2)

    assert decision.status == "human_check"


def test_arbiter_passes_clean_reviews():
    review = ClaimEvidenceReviewer().review(make_claim(), SOURCE_TEXT)

    decision = Arbiter().decide([review], total_claims=1)

    assert decision.status == "pass"
